// apps/consumer-angular/src/app.component.ts
import { Component, ElementRef, signal, viewChild } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import {
  PfAvatar,
  PfBadge,
  PfBadgeGroup,
  PfButton,
  PfCalendar,
  PfCard,
  PfCardContent,
  PfCardFooter,
  PfCardHeader,
  PfCheckbox,
  PfCommandGroup,
  PfCommandItem,
  PfCommandPalette,
  PfCombobox,
  PfContentDivider,
  PfDatePicker,
  PfDateRangePicker,
  PfContextMenu,
  PfCreditCard,
  PfDropdown,
  PfIcon,
  PfInput,
  PfKbd,
  PfLoadingDots,
  PfLoadingSkeleton,
  PfLoadingSpinner,
  PfMenuItem,
  PfMenuSeparator,
  PfModal,
  PfModalBody,
  PfModalFooter,
  PfModalHeader,
  PfMultiSelect,
  PfNotification,
  PfPagination,
  PfPopover,
  PfProgressBar,
  PfProgressCircle,
  PfRadioButton,
  PfOption,
  PfRadioGroup,
  PfScrollArea,
  PfSelect,
  PfSlideoutMenu,
  PfSlider,
  PfSwitch,
  PfTag,
  PfTagInput,
  PfTextarea,
  PfTimePicker,
  PfToaster,
  PfToolbar,
  PfTooltip,
  PfToolbarSeparator,
  PfUtilityButton,
  PfVisuallyHidden,
  TextValueAccessor,
  BooleanValueAccessor,
  NumericValueAccessor,
} from '@pitchfork-ui/elements-angular';

/**
 * Every element the library ships, used the way an Angular application would —
 * including a reactive form bound through the generated ControlValueAccessor,
 * which is the capability Stencil was chosen for.
 */
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    PfAvatar,
    PfBadge,
    PfBadgeGroup,
    PfButton,
    PfCalendar,
    PfCard,
    PfCardContent,
    PfCardFooter,
    PfCardHeader,
    PfCheckbox,
    PfCommandGroup,
    PfCommandItem,
    PfCommandPalette,
    PfCombobox,
    PfContentDivider,
    PfDatePicker,
    PfDateRangePicker,
    PfContextMenu,
    PfCreditCard,
    PfDropdown,
    PfIcon,
    PfInput,
    PfKbd,
    PfLoadingDots,
    PfLoadingSkeleton,
    PfLoadingSpinner,
    PfMenuItem,
    PfMenuSeparator,
    PfModal,
    PfModalBody,
    PfModalFooter,
    PfModalHeader,
    PfMultiSelect,
    PfNotification,
    PfPagination,
    PfPopover,
    PfProgressBar,
    PfProgressCircle,
    PfRadioButton,
    PfOption,
    PfRadioGroup,
    PfScrollArea,
    PfSelect,
    PfSlideoutMenu,
    PfSlider,
    PfSwitch,
    PfTag,
    PfTagInput,
    PfTextarea,
    PfTimePicker,
    PfToaster,
    PfToolbar,
    PfTooltip,
    PfToolbarSeparator,
    PfUtilityButton,
    PfVisuallyHidden,
    TextValueAccessor,
    BooleanValueAccessor,
    NumericValueAccessor,
  ],
  template: `
    <main data-testid="app">
      <h1><pf-icon name="circle-check" label="Working"></pf-icon> Angular consumer</h1>

      <div class="row">
        <pf-button variant="primary">Save</pf-button>
        <pf-button variant="secondary">Cancel</pf-button>
        <pf-button variant="ghost">Skip</pf-button>
        <pf-button variant="destructive">Delete</pf-button>
        <pf-button variant="primary" [loading]="true">Saving</pf-button>
      </div>

      <div class="row">
        <pf-badge>neutral</pf-badge>
        <pf-badge variant="brand">brand</pf-badge>
        <pf-badge variant="success">success</pf-badge>
        <pf-badge variant="warning">warning</pf-badge>
        <pf-badge variant="danger">danger</pf-badge>
      </div>

      <div class="row">
        @for (tag of tags(); track tag) {
          <pf-tag variant="brand" [dismissible]="true" (pfDismiss)="removeTag(tag)">
            {{ tag }}
          </pf-tag>
        }
      </div>

      <div class="row">
        <pf-avatar name="Ada Lovelace"></pf-avatar>
        <pf-avatar name="Ada Lovelace" size="lg" status="online"></pf-avatar>
        <pf-avatar size="xl"></pf-avatar>
      </div>

      <div class="row">
        <pf-kbd>Esc</pf-kbd>
        <pf-kbd size="sm" [keys]="['⌘', 'K']"></pf-kbd>
      </div>

      <div class="row">
        <pf-input
          label="Email"
          description="Bound with formControl, through the generated value accessor."
          [formControl]="email"
        ></pf-input>
        <p data-testid="echo">{{ email.value }}</p>
      </div>

      <pf-content-divider></pf-content-divider>

      <pf-card>
        <pf-card-header>
          <strong>Card</strong>
          <pf-visually-hidden> (a grouping surface)</pf-visually-hidden>
        </pf-card-header>
        <pf-card-content>
          Three sections, each its own element. A card using only some of them still renders
          correctly.
        </pf-card-content>
        <pf-card-footer>
          <pf-button variant="secondary">Dismiss</pf-button>
          <pf-button variant="primary">Confirm</pf-button>
        </pf-card-footer>
      </pf-card>

      <pf-content-divider>or</pf-content-divider>

      <pf-card>
        <pf-card-content>A card with content alone — no header, no footer.</pf-card-content>
      </pf-card>

      <div class="row">
        <pf-loading-spinner></pf-loading-spinner>
        <pf-loading-spinner [size]="40" label="Fetching"></pf-loading-spinner>
        <pf-loading-dots size="sm"></pf-loading-dots>
        <pf-loading-dots></pf-loading-dots>
        <pf-loading-dots size="lg"></pf-loading-dots>
      </div>

      <div class="row">
        <pf-loading-skeleton [width]="160" [height]="12"></pf-loading-skeleton>
        <pf-loading-skeleton width="40%" [rounded]="true"></pf-loading-skeleton>
      </div>

      <div class="row">
        <!-- Icon-only, label-only and both: the three slot combinations. -->
        <pf-utility-button label="Search">
          <pf-icon slot="icon" name="magnifying-glass"></pf-icon>
        </pf-utility-button>
        <pf-utility-button variant="brand">Archive</pf-utility-button>
        <pf-utility-button variant="destructive" size="sm">
          <pf-icon slot="icon" name="circle-xmark"></pf-icon>
          Delete
        </pf-utility-button>
      </div>

      <div class="row">
        <pf-badge-group label="2 new" message="See what changed" color="brand"></pf-badge-group>
        <pf-badge-group
          label="Beta"
          message="Try it out"
          color="success"
          appearance="modern"
          badge-position="trailing"
        ></pf-badge-group>
      </div>

      <div class="row">
        <!-- 30 of 60 is half drawn but must announce 30, not 50. -->
        <pf-progress-bar [value]="30" [max]="60" label="Upload"></pf-progress-bar>
        <pf-progress-circle [value]="75" label="Sync"></pf-progress-circle>
        <pf-progress-circle
          [value]="40"
          [size]="96"
          [strokeWidth]="10"
          [showValue]="false"
        ></pf-progress-circle>
      </div>

      <pf-credit-card
        brand="visa"
        card-number="4111111111111111"
        cardholder-name="Ada Lovelace"
        expiry="01/30"
        cvc="123"
      ></pf-credit-card>

      <!--
        One tab stop, then the arrows move within it. pf-button is not a native
        control, so it opts into the keyboard order with data-toolbar-item.
      -->
      <pf-toolbar>
        <pf-utility-button label="Search" data-toolbar-item>
          <pf-icon slot="icon" name="magnifying-glass"></pf-icon>
        </pf-utility-button>
        <pf-utility-button label="Download" data-toolbar-item>
          <pf-icon slot="icon" name="file-arrow-down"></pf-icon>
        </pf-utility-button>
        <pf-toolbar-separator></pf-toolbar-separator>
        <pf-button variant="ghost" data-toolbar-item>Share</pf-button>
      </pf-toolbar>

      <!-- Driven from Angular state: the element emits, the component decides. -->
      <pf-pagination
        [totalPages]="10"
        [page]="page()"
        (pfPageChange)="page.set($event.detail.page)"
      ></pf-pagination>
      <p data-testid="page-echo">page {{ page() }}</p>

      <!--
        The wave Stencil was chosen for: both bind with formControlName through
        a generated BooleanValueAccessor, and requiredTrue drives validation.
      -->
      <form [formGroup]="prefs" data-testid="prefs">
        <!--
          name and required alongside formControlName on purpose: Angular drives
          the value, and the native attributes keep the control in the browser's
          own submission and constraint validation. Both have to work.
        -->
        <pf-checkbox
          label="Accept terms"
          name="terms"
          required
          formControlName="terms"
        ></pf-checkbox>
        <pf-switch label="Email notifications" name="notify" formControlName="notify"></pf-switch>
        <pf-textarea label="Notes" name="notes" [rows]="3" formControlName="notes"></pf-textarea>
        <pf-slider
          label="Volume"
          name="volume"
          [min]="0"
          [max]="10"
          formControlName="volume"
        ></pf-slider>
        <!-- Form-associated, unlike the React DatePicker. -->
        <!-- One control, two submitted entries. -->
        <pf-date-range-picker
          label="Trip dates"
          name="trip"
          [value]="trip()"
          allow-clear
          data-testid="date-range-picker"
          (pfChange)="trip.set($event.detail.value)"
        ></pf-date-range-picker>
        <!-- Free text, with pf-tag chips. -->
        <pf-tag-input
          label="Topics"
          name="topics"
          [value]="topics()"
          [max]="5"
          data-testid="tag-input"
          (pfChange)="topics.set($event.detail.value)"
        ></pf-tag-input>

        <!-- One control, one submitted entry per value. -->
        <pf-multi-select
          label="Colours"
          name="colours"
          [value]="colours()"
          data-testid="multi-select"
          (pfChange)="colours.set($event.detail.value)"
        >
          <pf-option value="red">Red</pf-option>
          <pf-option value="green">Green</pf-option>
          <pf-option value="blue">Blue</pf-option>
          <pf-option value="grey" disabled>Grey</pf-option>
        </pf-multi-select>

        <!-- Shares pf-option with pf-select through the --pf-option-* bridge. -->
        <pf-combobox
          label="City"
          name="city"
          [value]="city()"
          data-testid="combobox"
          (pfChange)="city.set($event.detail.value)"
        >
          <pf-option value="berlin">Berlin</pf-option>
          <pf-option value="bristol">Bristol</pf-option>
          <pf-option value="cardiff">Cardiff</pf-option>
          <pf-option value="coventry" disabled>Coventry</pf-option>
        </pf-combobox>

        <!-- Children, not an options array; and typeahead. -->
        <pf-select
          label="Fruit"
          name="fruit"
          [value]="fruit()"
          data-testid="select"
          (pfChange)="fruit.set($event.detail.value)"
        >
          <pf-option value="apple">Apple</pf-option>
          <pf-option value="apricot">Apricot</pf-option>
          <pf-option value="banana">Banana <small>(in season)</small></pf-option>
          <pf-option value="blackberry" disabled>Blackberry</pf-option>
          <pf-option value="cherry">Cherry</pf-option>
        </pf-select>
        <!-- 12-hour display, 24-hour value. -->
        <pf-time-picker
          label="Start time"
          name="at"
          [value]="at()"
          [hourCycle]="12"
          [minuteStep]="15"
          data-testid="time-picker"
          (pfChange)="at.set($event.detail.value)"
        ></pf-time-picker>
        <pf-date-picker
          label="Due date"
          name="due"
          [value]="day()"
          min="2024-03-05"
          max="2024-03-26"
          allow-clear
          data-testid="date-picker"
          (pfChange)="day.set($event.detail.value)"
        ></pf-date-picker>
        <!--
          Children rendered with @for, not an options array. The group is the
          one form control; Angular never sees the radios inside it.
        -->
        <pf-radio-group legend="Plan" name="plan" formControlName="plan">
          @for (option of plans; track option.value) {
            <pf-radio-button [value]="option.value">{{ option.label }}</pf-radio-button>
          }
        </pf-radio-group>
      </form>
      <p data-testid="prefs-state">
        terms {{ prefs.controls.terms.value }} / notify {{ prefs.controls.notify.value }} / valid
        {{ prefs.valid }}
      </p>

      <!--
        Deliberately inside a clipping, stacking-context box: the panel is a
        popover, so it escapes both.
      -->
      <div
        data-testid="tooltip-clip"
        style="overflow: hidden; width: 120px; height: 40px; position: relative; z-index: 0"
      >
        <pf-tooltip [open]="true" placement="bottom">
          <button type="button">Anchored</button>
          <span slot="content">Escapes the clip box and the stacking context</span>
        </pf-tooltip>
      </div>
      <div style="position: relative; z-index: 999; height: 4px"></div>

      <div class="row">
        <!-- Light-dismiss and Escape come from the browser, not from us. -->
        <pf-popover label="Quick settings">
          <pf-button variant="secondary">Settings</pf-button>
          <div slot="content"><p style="margin: 0">Anchored, and dismissed by the browser.</p></div>
        </pf-popover>

        <pf-button variant="primary" (click)="modalOpen.set(true)">Open modal</pf-button>
      </div>

      <pf-modal
        [open]="modalOpen()"
        label="Confirm"
        (pfOpenChange)="modalOpen.set($event.detail.open)"
      >
        <pf-modal-header><strong>Confirm</strong></pf-modal-header>
        <pf-modal-body>
          A native dialog: the focus trap, Escape and the backdrop are the browser's. Only the
          page-scroll lock is ours.
        </pf-modal-body>
        <pf-modal-footer>
          <pf-button variant="secondary" (click)="modalOpen.set(false)">Cancel</pf-button>
          <pf-button variant="primary" (click)="modalOpen.set(false)">Confirm</pf-button>
        </pf-modal-footer>
      </pf-modal>

      <!--
        Both menus share pf-menu-item and pf-menu-separator; each container maps
        the generic --pf-menu-* set the item reads to its own alias family, so
        the same element is themed by whichever menu it sits in.
      -->
      <div class="row">
        <pf-dropdown
          label="Document actions"
          data-testid="dropdown"
          (pfSelect)="menuChoice.set($event.detail.value)"
        >
          <pf-button variant="secondary">Actions</pf-button>
          <pf-menu-item slot="menu" value="rename">
            Rename
            <pf-kbd slot="shortcut">F2</pf-kbd>
          </pf-menu-item>
          <pf-menu-item slot="menu" value="duplicate">Duplicate</pf-menu-item>
          <pf-menu-item slot="menu" value="archive" disabled>Archive</pf-menu-item>
          <pf-menu-separator slot="menu"></pf-menu-separator>
          <pf-menu-item slot="menu" value="delete" destructive>Delete</pf-menu-item>
        </pf-dropdown>

        <output data-testid="menu-choice">{{ menuChoice() || 'nothing chosen' }}</output>
      </div>

      <pf-context-menu
        label="Row actions"
        data-testid="context-menu"
        (pfSelect)="menuChoice.set($event.detail.value)"
      >
        <div style="border: 1px dashed var(--pf-surface-border); border-radius: 8px; padding: 16px">
          Right-click anywhere in this box.
        </div>
        <pf-menu-item slot="menu" value="open">Open</pf-menu-item>
        <pf-menu-item slot="menu" value="copy">
          Copy
          <pf-kbd slot="shortcut">Ctrl C</pf-kbd>
        </pf-menu-item>
        <pf-menu-separator slot="menu"></pf-menu-separator>
        <pf-menu-item slot="menu" value="remove" destructive>Remove</pf-menu-item>
      </pf-context-menu>

      <!--
        A slideout is a modal dialog pinned to an edge: showModal() gives the
        focus trap, Escape and the backdrop. Only the page-scroll lock is ours.
      -->
      <div class="row">
        <pf-button variant="secondary" (click)="slideoutOpen.set(true)">Open slideout</pf-button>
        <pf-button variant="primary" (click)="notify('success')">Toast</pf-button>
        <pf-button variant="secondary" (click)="notify('danger')">Toast a failure</pf-button>
      </div>

      <pf-slideout-menu
        [open]="slideoutOpen()"
        heading="Filters"
        description="Narrow the list down"
        (pfOpenChange)="slideoutOpen.set($event.detail.open)"
      >
        <p style="margin-top: 0">
          The heading is a prop rendered into the element's own shadow root, so this dialog names
          itself with aria-labelledby.
        </p>
        <pf-button slot="footer" variant="secondary" (click)="slideoutOpen.set(false)">
          Cancel
        </pf-button>
        <pf-button slot="footer" variant="primary" (click)="slideoutOpen.set(false)">
          Apply
        </pf-button>
      </pf-slideout-menu>

      <pf-notification
        variant="warning"
        heading="Scheduled maintenance"
        description="Saturday, 02:00-04:00 UTC."
        data-testid="page-notification"
      ></pf-notification>

      <pf-toaster #toaster placement="top-right" data-testid="toaster"></pf-toaster>

      <!--
        Options are slotted light DOM while the search input sits in the
        element's shadow root, so the active option is set as an element
        reference; a cross-root aria-activedescendant resolves to nothing.
      -->
      <div class="row">
        <pf-button variant="secondary" (click)="paletteOpen.set(true)">
          Open command palette
        </pf-button>
        <output data-testid="command-choice">{{ menuChoice() || 'nothing chosen' }}</output>
      </div>

      <pf-command-palette
        [open]="paletteOpen()"
        data-testid="command-palette"
        (pfOpenChange)="paletteOpen.set($event.detail.open)"
        (pfSelect)="menuChoice.set($event.detail.value)"
      >
        <pf-command-group label="File">
          <pf-command-item value="new">New file</pf-command-item>
          <pf-command-item value="open" description="Pick from recent">Open file</pf-command-item>
        </pf-command-group>
        <pf-command-group label="App">
          <pf-command-item value="settings">Settings</pf-command-item>
          <pf-command-item value="quit" disabled>Quit</pf-command-item>
        </pf-command-group>
      </pf-command-palette>

      <!-- One tab stop, arrows to move; see the React consumer for why. -->
      <div class="row">
        <pf-calendar
          [value]="day()"
          min="2024-03-05"
          max="2024-03-26"
          [startYear]="2020"
          [endYear]="2030"
          data-testid="calendar"
          (pfChange)="day.set($event.detail.value)"
        ></pf-calendar>
        <output data-testid="calendar-value">{{ day() }}</output>
      </div>

      <pf-scroll-area style="height: 80px; max-width: 280px">
        <p>
          A scroll area is focusable by default, so it can be scrolled with the arrow keys even when
          it holds no focusable child.
        </p>
        <p>Its scrollbar reserves a gutter rather than overlaying this text.</p>
        <p>Third paragraph, to make sure there is something to scroll to.</p>
      </pf-scroll-area>
    </main>
  `,
})
export class AppComponent {
  email = new FormControl('ada@example.com');
  tags = signal(['design', 'systems']);
  page = signal(3);
  modalOpen = signal(false);
  menuChoice = signal('');
  slideoutOpen = signal(false);
  paletteOpen = signal(false);
  day = signal('2024-03-15');
  at = signal('14:30');
  trip = signal('2024-03-10/2024-03-20');
  fruit = signal('banana');
  city = signal('');
  colours = signal('red,blue');
  topics = signal('design,systems');
  private toaster = viewChild<ElementRef<HTMLPfToasterElement>>('toaster');

  notify(variant: 'success' | 'danger') {
    void this.toaster()?.nativeElement.toast(
      variant === 'success'
        ? { variant, heading: 'Saved', description: 'Your changes are live.' }
        : {
            variant,
            heading: 'Upload failed',
            description: 'Announced assertively, unlike the success above.',
            duration: 0,
          },
    );
  }
  prefs = new FormGroup({
    terms: new FormControl(false, Validators.requiredTrue),
    notify: new FormControl(true),
    notes: new FormControl('first draft'),
    volume: new FormControl(7),
    plan: new FormControl('pro'),
  });

  plans = [
    { value: 'free', label: 'Free' },
    { value: 'pro', label: 'Pro' },
    { value: 'team', label: 'Team' },
  ];

  removeTag(tag: string) {
    this.tags.update((current) => current.filter((t) => t !== tag));
  }
}

// apps/consumer-react/src/App.tsx
import { useRef, useState } from 'react';
import {
  PfAvatar,
  PfBadge,
  PfBadgeGroup,
  PfButton,
  PfCalendar,
  PfCard,
  PfCardContent,
  PfCardFooter,
  PfCardHeader,
  PfCheckbox,
  PfCommandGroup,
  PfCommandItem,
  PfCommandPalette,
  PfCombobox,
  PfContentDivider,
  PfDatePicker,
  PfDateRangePicker,
  PfContextMenu,
  PfCreditCard,
  PfDropdown,
  PfIcon,
  PfInput,
  PfKbd,
  PfLoadingDots,
  PfLoadingSkeleton,
  PfLoadingSpinner,
  PfMenuItem,
  PfMenuSeparator,
  PfModal,
  PfModalBody,
  PfModalFooter,
  PfModalHeader,
  PfNotification,
  PfPagination,
  PfPopover,
  PfProgressBar,
  PfProgressCircle,
  PfRadioButton,
  PfOption,
  PfRadioGroup,
  PfScrollArea,
  PfSelect,
  PfSlideoutMenu,
  PfSlider,
  PfSwitch,
  PfTag,
  PfTextarea,
  PfTimePicker,
  PfToaster,
  PfToolbar,
  PfTooltip,
  PfToolbarSeparator,
  PfUtilityButton,
  PfVisuallyHidden,
} from '@pitchfork-ui/elements-react';

/**
 * Every element the library ships, used the way an application would. The
 * point is not to look good — it is that this file compiles, bundles and
 * renders styled output against the published wrapper package.
 */
export function App() {
  const [email, setEmail] = useState('ada@example.com');
  const [tags, setTags] = useState(['design', 'systems']);
  const [page, setPage] = useState(3);
  const [submitted, setSubmitted] = useState('');
  const [volume] = useState(7);
  const [modalOpen, setModalOpen] = useState(false);
  const [menuChoice, setMenuChoice] = useState('');
  const [slideoutOpen, setSlideoutOpen] = useState(false);
  const [paletteOpen, setPaletteOpen] = useState(false);
  const [day, setDay] = useState('2024-03-15');
  const [at, setAt] = useState('14:30');
  const [trip, setTrip] = useState('2024-03-10/2024-03-20');
  const [fruit, setFruit] = useState('banana');
  const [city, setCity] = useState('');
  const toaster = useRef<HTMLPfToasterElement>(null);
  const [plan, setPlan] = useState('pro');
  const plans = [
    { value: 'free', label: 'Free' },
    { value: 'pro', label: 'Pro' },
    { value: 'team', label: 'Team' },
  ];

  return (
    <main data-testid="app">
      <h1>
        <PfIcon name="circle-check" label="Working" /> React consumer
      </h1>

      <div className="row">
        <PfButton variant="primary">Save</PfButton>
        <PfButton variant="secondary">Cancel</PfButton>
        <PfButton variant="ghost">Skip</PfButton>
        <PfButton variant="destructive">Delete</PfButton>
        <PfButton variant="primary" loading>
          Saving
        </PfButton>
      </div>

      <div className="row">
        <PfBadge>neutral</PfBadge>
        <PfBadge variant="brand">brand</PfBadge>
        <PfBadge variant="success">success</PfBadge>
        <PfBadge variant="warning">warning</PfBadge>
        <PfBadge variant="danger">danger</PfBadge>
      </div>

      <div className="row">
        {tags.map((tag) => (
          <PfTag
            key={tag}
            variant="brand"
            dismissible
            onPfDismiss={() => setTags((current) => current.filter((t) => t !== tag))}
          >
            {tag}
          </PfTag>
        ))}
      </div>

      <div className="row">
        <PfAvatar name="Ada Lovelace" />
        <PfAvatar name="Ada Lovelace" size="lg" status="online" />
        <PfAvatar size="xl" />
      </div>

      <div className="row">
        <PfKbd>Esc</PfKbd>
        <PfKbd size="sm" keys={['⌘', 'K']} />
      </div>

      <div className="row">
        <PfInput
          label="Email"
          description="Changing this updates React state."
          value={email}
          onPfInput={(event) => setEmail(event.detail.value)}
        />
        <p data-testid="echo">{email}</p>
      </div>

      <PfContentDivider />

      <PfCard>
        <PfCardHeader>
          <strong>Card</strong>
          <PfVisuallyHidden> (a grouping surface)</PfVisuallyHidden>
        </PfCardHeader>
        <PfCardContent>
          Three sections, each its own element. A card using only some of them still renders
          correctly.
        </PfCardContent>
        <PfCardFooter>
          <PfButton variant="secondary">Dismiss</PfButton>
          <PfButton variant="primary">Confirm</PfButton>
        </PfCardFooter>
      </PfCard>

      <PfContentDivider>or</PfContentDivider>

      <PfCard>
        <PfCardContent>A card with content alone — no header, no footer.</PfCardContent>
      </PfCard>

      <div className="row">
        <PfLoadingSpinner />
        <PfLoadingSpinner size={40} label="Fetching" />
        <PfLoadingDots size="sm" />
        <PfLoadingDots />
        <PfLoadingDots size="lg" />
      </div>

      <div className="row">
        <PfLoadingSkeleton width={160} height={12} />
        <PfLoadingSkeleton width="40%" rounded />
      </div>

      <div className="row">
        {/* Icon-only, label-only and both: the three slot combinations. */}
        <PfUtilityButton label="Search">
          <PfIcon slot="icon" name="magnifying-glass" />
        </PfUtilityButton>
        <PfUtilityButton variant="brand">Archive</PfUtilityButton>
        <PfUtilityButton variant="destructive" size="sm">
          <PfIcon slot="icon" name="circle-xmark" />
          Delete
        </PfUtilityButton>
      </div>

      <div className="row">
        <PfBadgeGroup label="2 new" message="See what changed" color="brand" />
        <PfBadgeGroup
          label="Beta"
          message="Try it out"
          color="success"
          appearance="modern"
          badgePosition="trailing"
        />
      </div>

      <div className="row">
        {/* 30 of 60 is half drawn but must announce 30, not 50. */}
        <PfProgressBar value={30} max={60} label="Upload" />
        <PfProgressCircle value={75} label="Sync" />
        <PfProgressCircle value={40} size={96} strokeWidth={10} showValue={false} />
      </div>

      <PfCreditCard
        brand="visa"
        cardNumber="4111111111111111"
        cardholderName="Ada Lovelace"
        expiry="01/30"
        cvc="123"
      />

      {/*
        One tab stop, then the arrows move within it. pf-button is not a native
        control, so it opts into the keyboard order with data-toolbar-item.
      */}
      <PfToolbar>
        <PfUtilityButton label="Search" data-toolbar-item>
          <PfIcon slot="icon" name="magnifying-glass" />
        </PfUtilityButton>
        <PfUtilityButton label="Download" data-toolbar-item>
          <PfIcon slot="icon" name="file-arrow-down" />
        </PfUtilityButton>
        <PfToolbarSeparator />
        <PfButton variant="ghost" data-toolbar-item>
          Share
        </PfButton>
      </PfToolbar>

      {/* Uncontrolled: the element advances itself and reports where it went. */}
      <PfPagination
        totalPages={10}
        page={page}
        onPfPageChange={(event) => setPage(event.detail.page)}
      />
      <p data-testid="page-echo">page {page}</p>

      {/* Form-associated: these reach a real <form> through ElementInternals. */}
      <form
        data-testid="prefs"
        onSubmit={(event) => {
          event.preventDefault();
          const data = new FormData(event.currentTarget);
          setSubmitted([...data.keys()].sort().join(','));
        }}
      >
        <PfCheckbox name="terms" label="Accept terms" required />
        <PfSwitch name="notify" label="Email notifications" checked />
        <PfTextarea
          name="notes"
          label="Notes"
          description="Multi-line, form-associated."
          rows={3}
        />
        <PfSlider name="volume" label="Volume" min={0} max={10} value={volume} />
        {/*
          Form-associated, which the React DatePicker is not — its value only
          reaches a form if the consumer wires it there. In the form on
          purpose: the submission assertion is what caught an unreflected
          `name` on the other controls.
        */}
        {/*
          12-hour display, 24-hour value — the submission below proves it. The
          cycle is read through a getter, because an attribute of a
          union-literal type arrives as a string.
        */}
        {/*
          One control, two submitted entries: setFormValue accepts a FormData
          and submits every entry in it, so `trip-start` and `trip-end` both
          appear below.
        */}
        <PfDateRangePicker
          label="Trip dates"
          name="trip"
          value={trip}
          allowClear
          data-testid="date-range-picker"
          onPfChange={(event) => setTrip(event.detail.value)}
        />
        {/*
          Shares pf-option with pf-select: the option reads a generic
          --pf-option-* set that each listbox maps to its own family, so one
          element is themed by whichever container it is slotted into.
        */}
        <PfCombobox
          label="City"
          name="city"
          value={city}
          data-testid="combobox"
          onPfChange={(event) => setCity(event.detail.value)}
        >
          <PfOption value="berlin">Berlin</PfOption>
          <PfOption value="bristol">Bristol</PfOption>
          <PfOption value="cardiff">Cardiff</PfOption>
          <PfOption value="coventry" disabled>
            Coventry
          </PfOption>
        </PfCombobox>

        {/*
          Wave 5's first: options are child elements, so a label is a slot and
          can hold markup — which an `options` array of strings cannot. It also
          has typeahead, which the React Select does not.
        */}
        <PfSelect
          label="Fruit"
          name="fruit"
          value={fruit}
          data-testid="select"
          onPfChange={(event) => setFruit(event.detail.value)}
        >
          <PfOption value="apple">Apple</PfOption>
          <PfOption value="apricot">Apricot</PfOption>
          <PfOption value="banana">
            Banana <small>(in season)</small>
          </PfOption>
          <PfOption value="blackberry" disabled>
            Blackberry
          </PfOption>
          <PfOption value="cherry">Cherry</PfOption>
        </PfSelect>
        <PfTimePicker
          label="Start time"
          name="at"
          value={at}
          hourCycle={12}
          minuteStep={15}
          data-testid="time-picker"
          onPfChange={(event) => setAt(event.detail.value)}
        />
        <PfDatePicker
          label="Due date"
          name="due"
          value={day}
          min="2024-03-05"
          max="2024-03-26"
          allowClear
          data-testid="date-picker"
          onPfChange={(event) => setDay(event.detail.value)}
        />
        {/*
          Children, not an options array — the decision for every data-driven
          element in this layer. The cost is the map; the gain is that a
          choice's label is a slot, so it can hold anything.
        */}
        <PfRadioGroup
          name="plan"
          legend="Plan"
          value={plan}
          onPfChange={(e) => setPlan(e.detail.value)}
        >
          {plans.map((option) => (
            <PfRadioButton key={option.value} value={option.value}>
              {option.label}
            </PfRadioButton>
          ))}
        </PfRadioGroup>
        <PfButton type="submit" variant="primary">
          Save
        </PfButton>
      </form>
      <p data-testid="submitted">submitted: {submitted}</p>

      {/*
        Deliberately inside a clipping, stacking-context box: the panel is a
        popover, so it escapes both. A plain positioned element here would be
        cut off and lose to the z-index below it.
      */}
      <div
        data-testid="tooltip-clip"
        style={{
          overflow: 'hidden',
          width: '120px',
          height: '40px',
          position: 'relative',
          zIndex: 0,
        }}
      >
        <PfTooltip open placement="bottom">
          <button type="button">Anchored</button>
          <span slot="content">Escapes the clip box and the stacking context</span>
        </PfTooltip>
      </div>
      <div style={{ position: 'relative', zIndex: 999, height: '4px' }} />

      <div className="row">
        {/* Light-dismiss and Escape come from the browser, not from us. */}
        <PfPopover label="Quick settings">
          <PfButton variant="secondary">Settings</PfButton>
          <div slot="content">
            <p style={{ margin: 0 }}>Anchored, and dismissed by the browser.</p>
          </div>
        </PfPopover>

        <PfButton variant="primary" onClick={() => setModalOpen(true)}>
          Open modal
        </PfButton>
      </div>

      <PfModal
        open={modalOpen}
        label="Confirm"
        onPfOpenChange={(event) => setModalOpen(event.detail.open)}
      >
        <PfModalHeader>
          <strong>Confirm</strong>
        </PfModalHeader>
        <PfModalBody>
          A native dialog: the focus trap, Escape and the backdrop are the browser&rsquo;s. Only the
          page-scroll lock is ours.
        </PfModalBody>
        <PfModalFooter>
          <PfButton variant="secondary" onClick={() => setModalOpen(false)}>
            Cancel
          </PfButton>
          <PfButton variant="primary" onClick={() => setModalOpen(false)}>
            Confirm
          </PfButton>
        </PfModalFooter>
      </PfModal>

      {/*
        Both menus share pf-menu-item and pf-menu-separator. The item reads a
        generic `--pf-menu-*` set which each container maps to its own alias
        family, so the same element is themed by whichever menu it sits in --
        an inheritance that only a real stylesheet exercises, which is why it
        is asserted here and not in the browser project.
      */}
      <div className="row">
        <PfDropdown
          label="Document actions"
          data-testid="dropdown"
          onPfSelect={(event) => setMenuChoice(event.detail.value)}
        >
          <PfButton variant="secondary">Actions</PfButton>
          <PfMenuItem slot="menu" value="rename">
            Rename
            <PfKbd slot="shortcut">F2</PfKbd>
          </PfMenuItem>
          <PfMenuItem slot="menu" value="duplicate">
            Duplicate
          </PfMenuItem>
          <PfMenuItem slot="menu" value="archive" disabled>
            Archive
          </PfMenuItem>
          <PfMenuSeparator slot="menu" />
          <PfMenuItem slot="menu" value="delete" destructive>
            Delete
          </PfMenuItem>
        </PfDropdown>

        <output data-testid="menu-choice">{menuChoice || 'nothing chosen'}</output>
      </div>

      <PfContextMenu
        label="Row actions"
        data-testid="context-menu"
        onPfSelect={(event) => setMenuChoice(event.detail.value)}
      >
        <div
          style={{
            border: '1px dashed var(--pf-surface-border)',
            borderRadius: '8px',
            padding: 'var(--space-4)',
          }}
        >
          Right-click anywhere in this box.
        </div>
        <PfMenuItem slot="menu" value="open">
          Open
        </PfMenuItem>
        <PfMenuItem slot="menu" value="copy">
          Copy
          <PfKbd slot="shortcut">Ctrl C</PfKbd>
        </PfMenuItem>
        <PfMenuSeparator slot="menu" />
        <PfMenuItem slot="menu" value="remove" destructive>
          Remove
        </PfMenuItem>
      </PfContextMenu>

      {/*
        A slideout is a modal dialog pinned to an edge, so showModal() supplies
        the focus trap, Escape and the backdrop. Only the page-scroll lock is
        ours, and it is reference-counted in core so a slideout over a modal
        cannot leave the page stuck.
      */}
      <div className="row">
        <PfButton variant="secondary" onClick={() => setSlideoutOpen(true)}>
          Open slideout
        </PfButton>

        <PfButton
          variant="primary"
          onClick={() =>
            void toaster.current?.toast({
              variant: 'success',
              heading: 'Saved',
              description: 'Your changes are live.',
            })
          }
        >
          Toast
        </PfButton>

        <PfButton
          variant="secondary"
          onClick={() =>
            void toaster.current?.toast({
              variant: 'danger',
              heading: 'Upload failed',
              description: 'Announced assertively, unlike the success above.',
              duration: 0,
            })
          }
        >
          Toast a failure
        </PfButton>
      </div>

      <PfSlideoutMenu
        open={slideoutOpen}
        heading="Filters"
        description="Narrow the list down"
        onPfOpenChange={(event) => setSlideoutOpen(event.detail.open)}
      >
        <p style={{ marginTop: 0 }}>
          The heading above is a prop rendered into the element&rsquo;s own shadow root, so this
          dialog can name itself with <code>aria-labelledby</code> — which pf-modal cannot, because
          its header is slotted light DOM.
        </p>
        <PfButton slot="footer" variant="secondary" onClick={() => setSlideoutOpen(false)}>
          Cancel
        </PfButton>
        <PfButton slot="footer" variant="primary" onClick={() => setSlideoutOpen(false)}>
          Apply
        </PfButton>
      </PfSlideoutMenu>

      {/* A notification in the page, rather than in response to an action. */}
      <PfNotification
        variant="warning"
        heading="Scheduled maintenance"
        description="Saturday, 02:00–04:00 UTC."
        data-testid="page-notification"
      />

      <PfToaster ref={toaster} placement="top-right" data-testid="toaster" />

      {/*
        The command palette's options are slotted light-DOM children, and the
        search input is in the element's shadow root, so the active option is
        pointed at with `ariaActiveDescendantElement` rather than an IDREF --
        a cross-root `aria-activedescendant` is absent from the accessibility
        tree entirely. Grouping is structural for the same reason: one <slot>
        renders every child in source order, so a shadow root cannot box a
        subset of them.
      */}
      <div className="row">
        <PfButton variant="secondary" onClick={() => setPaletteOpen(true)}>
          Open command palette
        </PfButton>
        <output data-testid="command-choice">{menuChoice || 'nothing chosen'}</output>
      </div>

      <PfCommandPalette
        open={paletteOpen}
        data-testid="command-palette"
        onPfOpenChange={(event) => setPaletteOpen(event.detail.open)}
        onPfSelect={(event) => setMenuChoice(event.detail.value)}
      >
        <PfCommandGroup label="File">
          <PfCommandItem value="new">New file</PfCommandItem>
          <PfCommandItem value="open" description="Pick from recent">
            Open file
          </PfCommandItem>
        </PfCommandGroup>
        <PfCommandGroup label="App">
          <PfCommandItem value="settings">Settings</PfCommandItem>
          <PfCommandItem value="quit" disabled>
            Quit
          </PfCommandItem>
        </PfCommandGroup>
      </PfCommandPalette>

      {/*
        One tab stop and arrow-key movement, which the React Calendar does not
        have — it renders 42 buttons and no key handling. The arithmetic is
        core's, so both layers can agree once React adopts it.
      */}
      <div className="row">
        <PfCalendar
          value={day}
          min="2024-03-05"
          max="2024-03-26"
          startYear={2020}
          endYear={2030}
          data-testid="calendar"
          onPfChange={(event) => setDay(event.detail.value)}
        />
        <output data-testid="calendar-value">{day}</output>
      </div>

      <PfScrollArea style={{ height: '80px', maxWidth: '280px' }}>
        <p>
          A scroll area is focusable by default, so it can be scrolled with the arrow keys even when
          it holds no focusable child.
        </p>
        <p>Its scrollbar reserves a gutter rather than overlaying this text.</p>
        <p>Third paragraph, to make sure there is something to scroll to.</p>
      </PfScrollArea>
    </main>
  );
}
